@startuml testFileDatabase
entity User {
    UserID
    Name
    Password
}

entity TextFilesList {
    FileID
    FileName
    UserID
    Update
}

entity Marker{
  MarkerID
  Name
  Color
}


entity MarkingLog{
  MarkerID
  FileID
  HeadIndex
  Lenght  
}
entity EditText{
  FileID
  Text
  }

TextFilesList ||--ri--o{ User
TextFilesList ||-le-|| MarkingLog
TextFilesList ||-do-|{ Text
MarkingLog }o-le-|| Marker
@enduml